#pragma once
#include "HTTPSProxy.h"

const bytes HawkErrorPage("HTTP/1.1 200 OK\r\n"
	"Content - Type: text / html\r\n"
	"Content - Length : 645\r\n"
	"Connection : close<!DOCTYPE html>\r\n\r\n"
	"<html lang=\"en\">\n"
	"<head>\n"
	"    <meta charset=\"UTF-8\">\n"
	"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
	"    <title>HAWK Error Page</title>\n"
	"    <style>\n"
	"        /* Reset and basic styles */\n"
	"        body {\n"
	"            margin: 0;\n"
	"            padding: 0;\n"
	"            font-family: \"Arial\", sans-serif;\n"
	"            background-color: #f4f4f4;\n"
	"            color: #333;\n"
	"            display: flex;\n"
	"            justify-content: center;\n"
	"            align-items: center;\n"
	"            height: 100vh;\n"
	"            text-align: center;\n"
	"        }\n"
	"\n"
	"        .container {\n"
	"            max-width: 800px;\n"
	"            background: white;\n"
	"            padding: 40px;\n"
	"            border-radius: 12px;\n"
	"            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\n"
	"        }\n"
	"\n"
	"        h1 {\n"
	"            font-size: 48px;\n"
	"            margin-bottom: 10px;\n"
	"            color: #2c3e50;\n"
	"        }\n"
	"\n"
	"        p {\n"
	"            font-size: 18px;\n"
	"            line-height: 1.6;\n"
	"            color: #555;\n"
	"        }\n"
	"\n"
	"        .button {\n"
	"            display: inline-block;\n"
	"            margin-top: 20px;\n"
	"            padding: 12px 24px;\n"
	"            font-size: 18px;\n"
	"            color: white;\n"
	"            background: #3498db;\n"
	"            border: none;\n"
	"            border-radius: 6px;\n"
	"            text-decoration: none;\n"
	"            transition: 0.3s;\n"
	"        }\n"
	"\n"
	"        .button:hover {\n"
	"            background: #2980b9;\n"
	"        }\n"
	"    </style>\n"
	"</head>\n"
	"<body>\n"
	"\n"
	"    <div class=\"container\">\n"
	"        <h1>Hawk Error</h1>\n"
	"        <p>HAWK could not get requested site! try again!</p>\n"
	"        \n"
	"    </div>\n"
	"\n"
	"</body>\n"
	"</html>");

